[build]
  base = "/"
  publish = "/out"
  command = "npm run build"
  functions = "/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  SANITY_PROJECT_ID="wvv7gbzb"
  SANITY_DATASET="production"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "sanity"
  CL_CLIENT_ID = "ETpqt0R5oIDG8BgttE4idgGMkR6PeOkBCNnRhp-nvGk"
  CL_ENDPOINT = "https://demo.commercelayer.io"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    buildEvent = "onBuild"